blank_issues_enabled: false
contact_links:
  - name: Support
    url: https://github.com/jrappen/.github/blob/master/SUPPORT.md
    about: FAQ regarding support. Refer to the community health files repo.
  - name: Security Policy
    url: https://github.com/jrappen/.github/blob/master/SECURITY.md
    about: FAQ regarding security policy. Refer to the community health files repo.
