blank_issues_enabled: false
contact_links:
  - name: Community Support
    url: https://github.com/jrappen/.github/blob/master/SUPPORT.md
    about: Please ask and answer questions here.
  - name: Community Security Policy
    url: https://github.com/jrappen/.github/blob/master/SECURITY.md
    about: Please read more about how to report security vulnerabilities here.
